///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2318d45c-f57b-49a6-b453-44a9724e0a06")]
    public partial class MyTest1Repository : RepoGenBaseFolder
    {
        static MyTest1Repository instance = new MyTest1Repository();
        MyTest1RepositoryFolders.MotDePasseAppFolder _motdepasse;
        MyTest1RepositoryFolders.SetupOCM9999991AppFolder _setupocm9999991;
        MyTest1RepositoryFolders.SettingsOcmAppFolder _settingsocm;
        MyTest1RepositoryFolders.ConfirmerAppFolder _confirmer;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("2318d45c-f57b-49a6-b453-44a9724e0a06")]
        public static MyTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest1Repository() 
            : base("MyTest1Repository", "/", null, 0, false, "2318d45c-f57b-49a6-b453-44a9724e0a06", ".\\RepositoryImages\\MyTest1Repository2318d45c.rximgres")
        {
            _motdepasse = new MyTest1RepositoryFolders.MotDePasseAppFolder(this);
            _setupocm9999991 = new MyTest1RepositoryFolders.SetupOCM9999991AppFolder(this);
            _settingsocm = new MyTest1RepositoryFolders.SettingsOcmAppFolder(this);
            _confirmer = new MyTest1RepositoryFolders.ConfirmerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2318d45c-f57b-49a6-b453-44a9724e0a06")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MotDePasse folder.
        /// </summary>
        [RepositoryFolder("e85a4d58-d245-4598-bf83-97f5116f00d7")]
        public virtual MyTest1RepositoryFolders.MotDePasseAppFolder MotDePasse
        {
            get { return _motdepasse; }
        }

        /// <summary>
        /// The SetupOCM9999991 folder.
        /// </summary>
        [RepositoryFolder("b45d35e6-ae80-4737-ae3d-5bfdf991e199")]
        public virtual MyTest1RepositoryFolders.SetupOCM9999991AppFolder SetupOCM9999991
        {
            get { return _setupocm9999991; }
        }

        /// <summary>
        /// The SettingsOcm folder.
        /// </summary>
        [RepositoryFolder("9d7f9a0b-74f5-494a-8b06-3b4ec658fd82")]
        public virtual MyTest1RepositoryFolders.SettingsOcmAppFolder SettingsOcm
        {
            get { return _settingsocm; }
        }

        /// <summary>
        /// The Confirmer folder.
        /// </summary>
        [RepositoryFolder("bbc34124-4001-40f2-a2e7-f94eaca36865")]
        public virtual MyTest1RepositoryFolders.ConfirmerAppFolder Confirmer
        {
            get { return _confirmer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest1RepositoryFolders
    {
        /// <summary>
        /// The MotDePasseAppFolder folder.
        /// </summary>
        [RepositoryFolder("e85a4d58-d245-4598-bf83-97f5116f00d7")]
        public partial class MotDePasseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwordInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new MotDePasse  folder.
            /// </summary>
            public MotDePasseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MotDePasse", "/form[@name='GetPassword']", parentFolder, 30000, null, true, "e85a4d58-d245-4598-bf83-97f5116f00d7", "")
            {
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/text[@name='Password']", "?/?/text[@name='Password']", 30000, null, "5bf73cf3-9178-4ca1-a592-f32c9a00dac9");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@name='Btn_OK']", "?/?/button[@name='Btn_OK']", 30000, null, "f099db9b-373b-45dc-a0cd-bc61ca4d5566");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e85a4d58-d245-4598-bf83-97f5116f00d7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e85a4d58-d245-4598-bf83-97f5116f00d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("5bf73cf3-9178-4ca1-a592-f32c9a00dac9")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("5bf73cf3-9178-4ca1-a592-f32c9a00dac9")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("f099db9b-373b-45dc-a0cd-bc61ca4d5566")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("f099db9b-373b-45dc-a0cd-bc61ca4d5566")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The SetupOCM9999991AppFolder folder.
        /// </summary>
        [RepositoryFolder("b45d35e6-ae80-4737-ae3d-5bfdf991e199")]
        public partial class SetupOCM9999991AppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new SetupOCM9999991  folder.
            /// </summary>
            public SetupOCM9999991AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SetupOCM9999991", "/form[@name='MainForm']", parentFolder, 30000, null, true, "b45d35e6-ae80-4737-ae3d-5bfdf991e199", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b45d35e6-ae80-4737-ae3d-5bfdf991e199")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b45d35e6-ae80-4737-ae3d-5bfdf991e199")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The SettingsOcmAppFolder folder.
        /// </summary>
        [RepositoryFolder("9d7f9a0b-74f5-494a-8b06-3b4ec658fd82")]
        public partial class SettingsOcmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _quitterInfo;

            /// <summary>
            /// Creates a new SettingsOcm  folder.
            /// </summary>
            public SettingsOcmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SettingsOcm", "/contextmenu[@processname='SettingsOcm']", parentFolder, 30000, null, false, "9d7f9a0b-74f5-494a-8b06-3b4ec658fd82", "")
            {
                _quitterInfo = new RepoItemInfo(this, "Quitter", "?/?/menuitem[@accessiblename='Quitter']", "?/?/menuitem[@accessiblename='Quitter']", 30000, null, "73e516db-f7f8-455b-84b6-bfed823fb1fb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9d7f9a0b-74f5-494a-8b06-3b4ec658fd82")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9d7f9a0b-74f5-494a-8b06-3b4ec658fd82")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Quitter item.
            /// </summary>
            [RepositoryItem("73e516db-f7f8-455b-84b6-bfed823fb1fb")]
            public virtual Ranorex.MenuItem Quitter
            {
                get
                {
                    return _quitterInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Quitter item info.
            /// </summary>
            [RepositoryItemInfo("73e516db-f7f8-455b-84b6-bfed823fb1fb")]
            public virtual RepoItemInfo QuitterInfo
            {
                get
                {
                    return _quitterInfo;
                }
            }
        }

        /// <summary>
        /// The ConfirmerAppFolder folder.
        /// </summary>
        [RepositoryFolder("bbc34124-4001-40f2-a2e7-f94eaca36865")]
        public partial class ConfirmerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonouiInfo;

            /// <summary>
            /// Creates a new Confirmer  folder.
            /// </summary>
            public ConfirmerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Confirmer", "/form[@name='none']", parentFolder, 30000, null, true, "bbc34124-4001-40f2-a2e7-f94eaca36865", "")
            {
                _buttonouiInfo = new RepoItemInfo(this, "ButtonOui", "button[@name='Yes']", "button[@name='Yes']", 30000, null, "7f265953-3cb4-4554-a717-b940cb163d46");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bbc34124-4001-40f2-a2e7-f94eaca36865")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bbc34124-4001-40f2-a2e7-f94eaca36865")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOui item.
            /// </summary>
            [RepositoryItem("7f265953-3cb4-4554-a717-b940cb163d46")]
            public virtual Ranorex.Button ButtonOui
            {
                get
                {
                    return _buttonouiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOui item info.
            /// </summary>
            [RepositoryItemInfo("7f265953-3cb4-4554-a717-b940cb163d46")]
            public virtual RepoItemInfo ButtonOuiInfo
            {
                get
                {
                    return _buttonouiInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
